#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^10' state=follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
bspc rule -a mpv state=tilted follow=true
bspc rule -a qutebrowser desktop='^2' follow=false
bspc rule -a scratchpad sticky=on state=tilted hidden=on
st -c scratchpad -e ~/bin/scratch &
