#!/usr/bin/sh
# qemu-img create -f qcow2 freebsd.qcow2 15G                # create disk 
# Port 21 : ftpd
# Port 22 : sshd
# Port 23 : telnet
# Port 25 : smtp
# Port 80 : http
# Port 443: https
# Port 53 : DNS
# installer
# qemu-system-x86_64 -m 2048 \
#  -hda freebsd.qcow2 -enable-kvm \
#  -netdev user,id=mynet0,hostfwd=tcp:127.0.0.1:7722-:22 \

#  -device e1000,netdev=mynet0 \
#  -cdrom FreeBSD-12.1-RELEASE-amd64-disc1.iso

# run
sudo fuser -k 7721/tcp 7722/tcp 7723/tcp 7725/tcp  7780/tcp
qemu-system-x86_64 -m 6096 \
 -hda /mnt/sdb2/ubuntu.qcow2 -enable-kvm \
 -netdev user,id=mynet0,hostfwd=tcp:127.0.0.1:7722-:22,hostfwd=tcp:127.0.0.1:7780-:80,hostfwd=tcp:127.0.0.1:7725-:25,hostfwd=tcp:127.0.0.1:7721-:21,hostfwd=tcp:127.0.0.1:7723-:23 \
 -device e1000,netdev=mynet0
